### ISSUE TITLE
php 扩展，能直接使用 S 工具实现吗

### ISSUE THREAD

**Issue by rsonghuster** [awesome-fc/fc-faq#1]
https://developer.aliyun.com/article/746148?spm=a2c6h.12873581.0.0.1c001421tBn7Jh&groupCode=serverless

我实现的是 s 工具， 但是这个文档只是说了 fun 的使用方法， 请问下， 能提供 s 版本的帮助文档吗

**Comment by liulang0817** [comment]
可以通过s工具实现，通过s build 进行安装  https://help.aliyun.com/document_detail/295902.html

**Comment by rsonghuster** [comment]
> 可以通过s工具实现，通过s build 进行安装 https://help.aliyun.com/document_detail/295902.html

https://developer.aliyun.com/article/746148

先把这个文档改成使用 S 版本， 再录入到这个  repo 吧

**Comment by liulang0817** [comment]
新增了文档 ，介绍了自定义扩展使用和下载 https://github.com/awesome-fc/fc-faq/blob/main/docs/php%E8%BF%90%E8%A1%8C%E6%97%B6%E8%87%AA%E5%AE%9A%E4%B9%89%E6%89%A9%E5%B1%95%E4%BD%BF%E7%94%A8%E5%8F%8A%E4%B8%8B%E8%BD%BD.md

**Comment by rsonghuster** [comment]
看起来还可以
